Add design and logo
heigvd-software-engineering/heigvd-software-engineering.github.io pull request #10
Opened 2022-04-04 14:31 UTC by bchapuis

2022-04-04 15:43 UTC, Yahia1018 commented on _sass/hydeout/_layout.scss
> +  // background-image: linear-gradient(to bottom, lighten($sidebar-bg-color, 7%), darken($sidebar-bg-color, 7%));
I found the render with white background on computers nice, but not on mobile/tablet, the black background made a separation between the menu and the rest.

2022-04-04 15:43 UTC, Yahia1018 commented on _sass/hydeout/_layout.scss
> +    margin-bottom: 20px;
I would add a little bit more margin-bottom, like 25px or in rem 1.5rem, to be symetric with the padding above the logo. I found it nicer like that.

2022-04-04 15:43 UTC, Yahia1018 commented on _sass/hydeout/_layout.scss
> +  // text-align: center;
I found it better with "text-align: center" on mobile, and maybe with the logo in the center too ? And so, even without the black background, we could make a difference with menu and the rest of the page.

2022-04-04 15:43 UTC, Yahia1018 commented on _sass/hydeout/_layout.scss
> -#sidebar .site-title:hover {
There was too much red ?

2022-04-04 15:43 UTC, Yahia1018 commented on _sass/hydeout/_variables.scss
> +$sidebar-sticky: false !default;
I like the idea of the sidebar on the top.

2022-04-06 12:30 UTC, bchapuis commented on _sass/hydeout/_layout.scss
> +  // background-image: linear-gradient(to bottom, lighten($sidebar-bg-color, 7%), darken($sidebar-bg-color, 7%));
The heig-vd logo does not render well on a black background. Lets find a solution for this later.

2022-04-06 12:57 UTC, Yahia1018 commented on _sass/hydeout/_layout.scss
> +  // background-image: linear-gradient(to bottom, lighten($sidebar-bg-color, 7%), darken($sidebar-bg-color, 7%));
I purposed that in an another comment :

> I found it better with "text-align: center" on mobile, and maybe with the logo in the center too ? And so, even without the black background, we could make a difference with menu and the rest of the page.

2022-04-06 12:59 UTC, Yahia1018 requested changes
There are some propositions you didn't answer.

2022-04-06 13:05 UTC, Yahia1018 commented on _sass/hydeout/_layout.scss
> +  // background-image: linear-gradient(to bottom, lighten($sidebar-bg-color, 7%), darken($sidebar-bg-color, 7%));
![Capture d’écran 2022-04-06 à 15 04 49](https://user-images.githubusercontent.com/91720525/161981176-111d641a-3849-4700-a4eb-5f00a6a1ab44.png)

And with this background color ? As the repository logo.

2022-04-06 16:11 UTC, bchapuis commented on _sass/hydeout/_layout.scss
> +    margin-bottom: 20px;
Please go ahead with the space you like ;)

2022-04-06 16:11 UTC, bchapuis commented on _sass/hydeout/_layout.scss
> -#sidebar .site-title:hover {
yes

2022-04-08 10:48 UTC, Yahia1018 approved these changes

2022-04-08 12:58 UTC, merged